# FROM python:3.9-slim
# RUN python3 -m venv venv
# RUN . venv/bin/activate
# COPY requirements.txt .
# RUN pip install -r requirements.txt
# COPY main.py .
# CMD ["python", "main.py"]

FROM python:3.9-slim
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "main.py"]